name: CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - README.md
  pull_request:
    branches: ["main"]
    paths-ignore:
      - README.md
  workflow_call:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Setup the repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run the linter
        run: deno lint

      - name: Run tests
        run: deno task test

      - name: Check package's readiness of being published to JSR
        run: deno publish --dry-run
